### ISSUE TITLE
Error while deploying docker container

### ISSUE THREAD

**Issue by javiruizs** [ec-better/hackathon-2020-satcen#1]
Hi there!

First of all, I would like to thank you for this repository! It's being really helpful for my bachelor's thesis.

I just wanted to let you know that I've encountered a problem when trying to deploy the jupyter lab in docker.
I really don't know if something has changed during the past weeks, because I did this previously without any inconveniences, but I recently tried to do the process again in another machine and I bumped into a problem that has persisted since then.

I think it has to do with the conda package "cioppy" from the [Terradue repo](https://anaconda.org/terradue/repo?sort=_name&sort_order=asc) which has the access labeled as "None".

I'm attaching the captures for the command `docker-compose build` and for the satus of the mentioned package in the repo.

Kind regards,
javiruizs

Attachments:

- `docker-compose build`:

![dc-build](https://user-images.githubusercontent.com/25848800/102701579-a3f17e00-4258-11eb-8273-e1b6faeb0cc7.png)
- Package in the repo:
![dc-up](https://user-images.githubusercontent.com/25848800/102701578-a358e780-4258-11eb-9b7f-7fa2afda7b17.png)

**Comment by alunacob** [comment]
Hey @javiruizs. I will look into it with more time, since I think that dependency is deprecated and not used in the notebooks. 

As a quick reaction, maybe you can try to remove the cioppy package from the environment here: https://github.com/ec-better/hackathon-2020-satcen/blob/master/.binder/environment.yml#L6 and try to build the stack again?

Hope it helps while we look into fixing this.

**Comment by fabricebrito** [comment]
Hello @javiruizs, we had a small but annoying issue on the base docker image. I've updated it and got a successful build on Binder.
Let me know if it also works for you and I'll close the ticket

Cheers

**Comment by javiruizs** [comment]
Hello to both,

Issue is now solved. I saw you commited new changes so I pulled again and now it works!

Thanks to both of you!
